using Autodesk.Revit.DB;
using Autodesk.Revit.DB.ExtensibleStorage;

namespace Cda.Revit.Addin.Infrastructure;

/// <summary>
/// Durable, invisible ownership marks on elements this add-in generates.
///
/// WHY THIS REPLACES 'COMMENTS'
///   The skirting engine stamped its identity into the built-in Comments parameter. That
///   works exactly until a human uses Comments for what it is for. Three concrete failures,
///   all of which corrupt the tool's own bookkeeping:
///
///     * A user types a note into Comments on a generated board. The stamp is destroyed,
///       Regenerate no longer finds the board, and the next run leaves an orphan behind.
///     * A user copies a board and edits the copy's Comments. Now two elements claim the
///       same identity.
///     * Anyone scheduling Comments sees "DKSI skirting:1016:28361856:7" in a drawing.
///
///   Extensible Storage has none of those properties. It is invisible in the UI, cannot be
///   edited by hand, survives copy/paste, round-trips through synchronisation, and is typed
///   rather than parsed out of a string.
///
/// BACKWARD COMPATIBILITY
///   Models already carry Comments stamps from earlier runs. <see cref="Read"/> therefore
///   falls back to Comments when no entity is present, so a Regenerate over an existing
///   model still finds and removes what previous versions placed. New writes go to storage
///   only. The fallback can be deleted once no live model predates this change.
///
/// IDENTITY
///   The payload records UniqueId, not ElementId. ElementId is stable within one document
///   and nowhere else - it is reassigned by copy/paste between models, by e-transmit, and
///   by upgrade. UniqueId survives all three, which is what makes a stamp written today
///   still meaningful after the model has been through a project's real lifecycle.
/// </summary>
internal static class ElementStamp
{
    /// <summary>
    /// Fixed for the life of the add-in. Changing it orphans every stamp already written,
    /// exactly as changing a shared parameter GUID would.
    /// </summary>
    private static readonly Guid SchemaId = new("b1e7c40a-5d92-4f38-8a61-3c07d5e29b44");

    private const string SchemaName = "DksiGeneratedElement";
    private const string ToolField = "Tool";
    private const string TagField = "Tag";
    private const string SourceField = "SourceUniqueId";

    /// <summary>Must match the VendorId in the .addin manifest.</summary>
    private const string VendorId = "DKSI";

    private static Schema? _schema;

    /// <summary>
    /// The schema, created on first use. Schema creation is NOT a document modification -
    /// it registers in the session - so this needs no transaction. Writing an Entity to an
    /// element does, and that is the caller's responsibility.
    /// </summary>
    private static Schema? Resolve()
    {
        if (_schema is not null && _schema.IsValidObject) return _schema;

        try
        {
            _schema = Schema.Lookup(SchemaId);
            if (_schema is not null) return _schema;

            var builder = new SchemaBuilder(SchemaId);
            builder.SetSchemaName(SchemaName);
            builder.SetVendorId(VendorId);

            // Public read so a QA or audit add-in can inspect what we generated. Public
            // write because a vendor-restricted schema silently refuses writes when the
            // manifest VendorId and this constant drift apart, and that failure is invisible.
            builder.SetReadAccessLevel(AccessLevel.Public);
            builder.SetWriteAccessLevel(AccessLevel.Public);

            builder.AddSimpleField(ToolField, typeof(string));
            builder.AddSimpleField(TagField, typeof(string));
            builder.AddSimpleField(SourceField, typeof(string));

            _schema = builder.Finish();
            return _schema;
        }
        catch (Exception ex)
        {
            Log.Warn($"Extensible Storage schema unavailable, falling back to Comments: {ex.Message}");
            return null;
        }
    }

    /// <summary>
    /// Marks an element as generated by <paramref name="tool"/>. Caller owns the transaction.
    /// </summary>
    /// <param name="sourceUniqueId">
    /// The element this one was derived from - the wall a board sits on, the slab a ceiling
    /// mirrors. UniqueId so the link survives the model being copied or upgraded.
    /// </param>
    public static bool Write(Element element, string tool, string tag, string? sourceUniqueId = null)
    {
        var schema = Resolve();
        if (schema is null) return false;

        try
        {
            using var entity = new Entity(schema);

            entity.Set(ToolField, tool ?? string.Empty);
            entity.Set(TagField, tag ?? string.Empty);
            entity.Set(SourceField, sourceUniqueId ?? string.Empty);

            element.SetEntity(entity);
            return true;
        }
        catch (Exception ex)
        {
            Log.Warn($"Could not stamp element {element.Id.Value}: {ex.Message}");
            return false;
        }
    }

    /// <summary>
    /// Stamps an element, falling back to the legacy Comments field when storage is
    /// unavailable. Returns false only when NEITHER worked.
    ///
    /// WHY EVERY TOOL SHOULD GO THROUGH THIS RATHER THAN <see cref="Write"/> DIRECTLY
    ///   Write returns false and swallows its exception, which is right - a failed stamp must
    ///   not abort a placement run. But two callers ignored that return and had no fallback,
    ///   and the consequence was not cosmetic: both tools promise an idempotent re-run and
    ///   implement it by deleting their own stamped output first. An unstamped element is
    ///   invisible to that search, so the next "regenerate" leaves it standing AND places a
    ///   second one on top of it. For radiators it is worse again, because the orphans are
    ///   Mechanical Equipment and therefore register as obstructions in the new pass - so most
    ///   windows come back refused for "no space", naming a reason that is not the real one.
    ///
    ///   Both tools already declared a legacy Comments prefix, and both delete paths already
    ///   honoured it; nothing on the write side ever produced one. This closes that half, and
    ///   <see cref="Read"/> now hands back the same tag either way so a caller cannot tell
    ///   which path was used.
    /// </summary>
    /// <param name="legacyCommentsPrefix">
    /// Prefix identifying this tool's Comments stamps. Prepended to <paramref name="tag"/>
    /// unless the tag already carries it, so a tool whose tags are self-prefixed (the skirting
    /// generator's are) is not stamped twice over.
    /// </param>
    public static bool WriteOrFallback(
        Element element, string tool, string tag, string legacyCommentsPrefix,
        string? sourceUniqueId = null)
    {
        if (Write(element, tool, tag, sourceUniqueId)) return true;

        // Storage unavailable. Fall back so the run is still re-runnable, and accept that a
        // user editing Comments can break it - which is exactly the trade the skirting
        // generator has always made, now made once here for every tool.
        try
        {
            var parameter = element.get_Parameter(BuiltInParameter.ALL_MODEL_INSTANCE_COMMENTS);
            if (parameter is not { IsReadOnly: false }) return false;

            parameter.Set(tag.StartsWith(legacyCommentsPrefix, StringComparison.Ordinal)
                ? tag
                : legacyCommentsPrefix + tag);

            return true;
        }
        catch
        {
            // Unstamped: the caller's next run will not recognise this element as its own.
            return false;
        }
    }

    /// <summary>
    /// The tag this add-in wrote, or null. Falls back to the legacy Comments stamp so
    /// elements placed by earlier versions - and by <see cref="WriteOrFallback"/> on a model
    /// where storage is unavailable - are still recognised.
    ///
    /// THE COMMENTS PATH RETURNS THE TAG, NOT THE WHOLE COMMENT. It used to return the raw
    /// Comments string with the prefix still on it, which meant a caller comparing the result
    /// against its own tag never matched on that path: RoomDimensionGenerator tests for
    /// "&lt;room UniqueId&gt;|" and "DKSI room dimension:&lt;room UniqueId&gt;|..." does not
    /// start with that. Stripping the prefix makes both paths return the same thing, which is
    /// what lets a caller treat storage and Comments as interchangeable.
    /// </summary>
    public static string? Read(Element element, string tool, string legacyCommentsPrefix)
    {
        var schema = Resolve();

        if (schema is not null)
        {
            try
            {
                using var entity = element.GetEntity(schema);

                if (entity.IsValid() && entity.Get<string>(ToolField) == tool)
                    return entity.Get<string>(TagField);
            }
            catch
            {
                // Entity unreadable on this element; try the legacy path.
            }
        }

        try
        {
            var comments = element
                .get_Parameter(BuiltInParameter.ALL_MODEL_INSTANCE_COMMENTS)?.AsString();

            if (string.IsNullOrEmpty(comments) ||
                !comments.StartsWith(legacyCommentsPrefix, StringComparison.Ordinal))
                return null;

            return comments[legacyCommentsPrefix.Length..];
        }
        catch
        {
            return null;
        }
    }

    /// <summary>
    /// A quick filter matching only elements carrying this schema.
    ///
    /// This is the point of the whole exercise for performance: finding previously
    /// generated elements was a full sweep of every FamilyInstance in the model with a
    /// parameter read on each. An ExtensibleStorageFilter is evaluated natively.
    /// </summary>
    public static ElementFilter? Filter()
    {
        var schema = Resolve();
        return schema is null ? null : new ExtensibleStorageFilter(SchemaId);
    }
}
